baseurl                 = "https://keenanadams.me/"               # Your domain name. Must end with "/"
canonifyURLs            = true
languageCode            = "en-us"
title                   = "Keenan Adams"
author                  = "Keenan"
theme                   = "keen-i-am"
pygmentsStyle           = "manni"                     # https://help.farbox.com/pygments.html
pygmentsCodefences      = true
# googleAnalytics       = "xxx"             # Tracking code, eg. "UA-111111111-1"

[params]
    dateform            = "Mon Jan 02, 2006"
    dateformfull        = "Mon Jan 2 2006 15:04:05 EST"
    favicon             = "sam.ico"
    homepage            = "home"                        # What to call the home page link
    galleryFolder       = "images/"                     # Where you've put your images, after "/content/gallery/"
    clickablePhotos     = true                          # Allow links to the full size images
    footerText          = ""

# Metadata
    description         = "I'm a user experience designer and developer with a keen interest in designing technology for social good."            # Max 160 characters show in search results
    twitterCard         = "summary_large_image"         # Card value “summary”, “summary_large_image”, “app”, or “player”
    primaryImage        = "/tn.png"        a             # Image that shows on Twitter cards and OpenGraph links

[[params.mainMenu]]
    link = "/about"
    text = "who is keenan?"

[[params.mainMenu]]
     link = "/blog"
     text = "blog"

[[params.mainMenu]]
   link = "/folio"
   text = "folio"

# [[params.mainMenu]]
#    link = "/gallery"
#    text = "gallery"
